wip

diff --git a/.github/workflows/playwright-UI-tests.yml b/.github/workflows/playwright-UI-tests.yml
--- a/.github/workflows/playwright-UI-tests.yml
+++ b/.github/workflows/playwright-UI-tests.yml
@@ -30,31 +30,41 @@ jobs:
         uses: actions/setup-python@v5
         with:
           python-version: "3.12"
-      - run: |
-          ARTIFACT_ID=$(curl -L \
+      - name: Download artifacts
+        run: |
+          # Check if there are any artifacts
+          ARTIFACTS=$(curl -L \
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
-          "https://api.github.com/repos/Windrunner9638/playwright-python/actions/artifacts?name=allure_results" \
-          | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);") \
-          && \
+          "https://api.github.com/repos/Windrunner9638/playwright-python/actions/artifacts?name=allure_results")
+          
+          echo "Available artifacts:"
+          echo "$ARTIFACTS"
+          
+          if [[ $(echo "$ARTIFACTS" | python -c "import sys, json; print(json.load(sys.stdin)['total_count'])") == "0" ]]; then
+            echo "No artifacts found"
+            mkdir -p allure_results
+            exit 0
+          fi
+          
+          ARTIFACT_ID=$(echo "$ARTIFACTS" | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id'])")
+          echo "Found artifact ID: $ARTIFACT_ID"
+          
+          # Download the artifact
           curl -L \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.ACTIONS_TOKEN }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
-          https://api.github.com/repos/Windrunner9638/playwright-python/actions/artifacts/$ARTIFACT_ID/zip \
+          -v \
+          "https://api.github.com/repos/Windrunner9638/playwright-python/actions/artifacts/$ARTIFACT_ID/zip" \
           -o artifacts.zip
-      - name: Check if artifacts.zip exists and is valid
-        run: |
+          
+          # Create directory even if no previous artifacts exist
+          mkdir -p allure_results
+          
           if [ -f artifacts.zip ]; then
-            if unzip -t artifacts.zip; then
-              echo "artifacts.zip is a valid zip file."
-            else
-              echo "artifacts.zip is not a valid zip file."
-              exit 1
-            fi
-          else
-            echo "artifacts.zip does not exist."
-            exit 1
+            unzip -t artifacts.zip || echo "Invalid zip file"
+            unzip artifacts.zip -d allure_results || echo "Failed to unzip"
           fi
       - run: mkdir allure_results && unzip artifacts.zip -d allure_results
       - run: mkdir old_pages pages_history && unzip pages.zip -d old_pages && tar -xvf old_pages/artifact.tar -C pages_history
